name: Complex Workflow

on:
  workflow_dispatch:  # Trigger only manually

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the project
        run: echo "Building..."

  Test:
    runs-on: ubuntu-latest
    needs: Build  # Run after Build
    if: github.event_name == 'workflow_dispatch'  # Only runs if triggered manually
    environment: Test
    steps:
      - name: Run Test
        run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build  # Run after Build
    if: github.event_name == 'workflow_dispatch'  # Only runs if triggered manually
    environment: Load-Test
    steps:
      - name: Run Load Test
        run: |
          echo "Load testing..."
          sleep 15  # Simulating load test with a 15-second sleep

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]  # Run after Test and Load-Test
    if: github.event.inputs.deployment_env == 'Production'  # Run only if 'Production' input selected
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - name: Step 1
        run: |
          echo "Step 1 deploying..."
          sleep 10
      - name: Step 2
        run: |
          echo "Step 2 deploying..."
          sleep 10
      - name: Step 3
        run: |
          echo "Step 3 deploying..."
          sleep 10
      - name: Step 4
        run: |
          echo "Step 4 deploying..."
          sleep 10
      - name: Step 5
        run: |
          echo "Step 5 deploying..."
          sleep 10
